// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsyksllqaxvmcpgdkdhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzeWtzbGxxYXh2bWNwZ2RrZGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAzNDU3NDIsImV4cCI6MjA0NTkyMTc0Mn0.ZfWiUV_emiQ5ST1Y2pwoAoG4S4m-Yx3C3kGkPeItSQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);